
include $(SIMSCRIPTS_DIR)/mkfiles/plusargs.mk

TIMEOUT := 10ms

MK_INCLUDES += $(OC_WB_IP)/ve/wb_uart16550/sim/scripts/rules_defs.mk

TB=wb_uart16550_tb

include $(SIMSCRIPTS_DIR)/mkfiles/common_sim.mk


	
