
include $(PACKAGES_DIR)/packages.mk
include $(PACKAGES_DIR)/simscripts/mkfiles/plusargs.mk

TB=wb_periph_subsys_tb
TB_MODULES_HDL=wb_periph_subsys_tb_hdl
TB_MODULES_HVL=wb_periph_subsys_tb_hvl wb_periph_subsys_tests_pkg

include $(PACKAGES_DIR)/simscripts/mkfiles/common_sim.mk


	
