
include $(PACKAGES_DIR)/packages.mk
include $(PACKAGES_DIR)/simscripts/mkfiles/plusargs.mk

TB=wb_uart_tb
TB_MODULES_HDL=wb_uart_tb
# TB_MODULES_HDL=wb_if

include $(PACKAGES_DIR)/simscripts/mkfiles/common_sim.mk


	